<?php
require_once __DIR__ . '/includes/auth.php'; requireRole('user'); $uid=(int)$_SESSION['user_id']; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$food=trim((string)($_POST['food_name']??''));$meal=$_POST['meal_type']??'snack';$allowed=['breakfast','lunch','dinner','snack'];$nums=[];foreach(['calories','protein_g','carbs_g','fat_g'] as $k){$raw=trim((string)($_POST[$k]??''));$nums[$k]=$raw===''?null:filter_var($raw,FILTER_VALIDATE_FLOAT);}if($food===''||mb_strlen($food)>150)$error='Enter a food name up to 150 characters.';elseif(!in_array($meal,$allowed,true))$error='Choose a valid meal type.';else{$q=$pdo->prepare('INSERT INTO food_logs(user_id,meal_type,food_name,calories,protein_g,carbs_g,fat_g,notes) VALUES(?,?,?,?,?,?,?,?)');$q->execute([$uid,$meal,$food,$nums['calories']===null?null:max(0,(int)$nums['calories']),$nums['protein_g'],$nums['carbs_g'],$nums['fat_g'],trim((string)($_POST['notes']??''))?:null]);redirect('nutrition.php');}}
$q=$pdo->prepare('SELECT * FROM food_logs WHERE user_id=? ORDER BY logged_at DESC LIMIT 100');$q->execute([$uid]);$rows=$q->fetchAll();$q=$pdo->prepare('SELECT COALESCE(SUM(calories),0) FROM food_logs WHERE user_id=? AND DATE(logged_at)=CURDATE()');$q->execute([$uid]);$today=(int)$q->fetchColumn();$pageTitle='Nutrition';require __DIR__.'/includes/header.php';
?>
<section class="page-heading"><div><p class="eyebrow">FUEL YOUR DAY</p><h1>Nutrition tracker</h1><p>Log meals and keep track of nutrition values.</p></div></section>
<section class="stats-grid"><article class="stat-card"><p>Calories logged today</p><h2><?=$today?></h2></article></section>
<section class="panel"><h2>Log food</h2><?php if($error):?><div class="alert error"><?=escapeHtml($error)?></div><?php endif;?><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=escapeHtml(csrfToken())?>"><div><label>Food name</label><input name="food_name" maxlength="150" required></div><div><label>Meal</label><select name="meal_type"><option>breakfast</option><option>lunch</option><option>dinner</option><option>snack</option></select></div><?php foreach(['calories'=>'Calories','protein_g'=>'Protein (g)','carbs_g'=>'Carbs (g)','fat_g'=>'Fat (g)'] as $k=>$label):?><div><label><?=escapeHtml($label)?></label><input type="number" min="0" step="0.1" name="<?=escapeHtml($k)?>"></div><?php endforeach;?><div class="full"><label>Notes</label><textarea name="notes" rows="2"></textarea></div><div><button class="button" type="submit">Save food log</button></div></form></section>
<section class="panel"><h2>Food history</h2><?php if(!$rows):?><p>No meals logged yet.</p><?php else:?><div class="table-wrap"><table><thead><tr><th>Date</th><th>Meal</th><th>Food</th><th>Calories</th><th>Protein</th><th>Carbs</th><th>Fat</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=escapeHtml($r['logged_at'])?></td><td><?=escapeHtml(ucfirst($r['meal_type']))?></td><td><?=escapeHtml($r['food_name'])?></td><td><?=escapeHtml((string)($r['calories']??'—'))?></td><td><?=escapeHtml((string)($r['protein_g']??'—'))?></td><td><?=escapeHtml((string)($r['carbs_g']??'—'))?></td><td><?=escapeHtml((string)($r['fat_g']??'—'))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php require __DIR__.'/includes/footer.php';?>
