<?php
require_once __DIR__.'/includes/auth.php'; requireRole('user'); $uid=(int)$_SESSION['user_id'];$error='';$success='';
$q=$pdo->prepare('SELECT name,email,age,gender,height_cm,weight_kg,fitness_level FROM users WHERE id=?');$q->execute([$uid]);$user=$q->fetch();
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$name=trim((string)($_POST['name']??''));$ageRaw=trim((string)($_POST['age']??''));$heightRaw=trim((string)($_POST['height_cm']??''));$weightRaw=trim((string)($_POST['weight_kg']??''));$gender=$_POST['gender']??'';$level=$_POST['fitness_level']??'beginner';$age=$ageRaw===''?null:filter_var($ageRaw,FILTER_VALIDATE_INT);$height=$heightRaw===''?null:filter_var($heightRaw,FILTER_VALIDATE_FLOAT);$weight=$weightRaw===''?null:filter_var($weightRaw,FILTER_VALIDATE_FLOAT);
if($name===''||mb_strlen($name)>100)$error='Enter a name up to 100 characters.';elseif($ageRaw!==''&&($age===false||$age<1||$age>120))$error='Age must be between 1 and 120.';elseif($heightRaw!==''&&($height===false||$height<1||$height>300))$error='Enter a valid height.';elseif($weightRaw!==''&&($weight===false||$weight<1||$weight>500))$error='Enter a valid weight.';elseif(!in_array($gender,['','male','female','other','prefer_not_to_say'],true)||!in_array($level,['beginner','intermediate','advanced'],true))$error='Choose valid profile options.';else{$q=$pdo->prepare('UPDATE users SET name=?,age=?,gender=?,height_cm=?,weight_kg=?,fitness_level=? WHERE id=?');$q->execute([$name,$age,$gender?:null,$height,$weight,$level,$uid]);$_SESSION['user_name']=$name;$success='Profile updated.';$q=$pdo->prepare('SELECT name,email,age,gender,height_cm,weight_kg,fitness_level FROM users WHERE id=?');$q->execute([$uid]);$user=$q->fetch();}}
$pageTitle='Profile';require __DIR__.'/includes/header.php';
?>
<section class="page-heading"><div><p class="eyebrow">YOUR ACCOUNT</p><h1>Profile settings</h1><p>Manage your personal profile information.</p></div></section>
<section class="panel narrow-panel"><h2>Personal information</h2><?php if($error):?><div class="alert error"><?=escapeHtml($error)?></div><?php endif;?><?php if($success):?><div class="alert success"><?=escapeHtml($success)?></div><?php endif;?>
<form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=escapeHtml(csrfToken())?>"><div class="full"><label>Full name</label><input name="name" maxlength="100" value="<?=escapeHtml($user['name'])?>" required></div><div class="full"><label>Email</label><input value="<?=escapeHtml($user['email'])?>" disabled></div><div><label>Age</label><input name="age" type="number" min="1" max="120" value="<?=escapeHtml((string)($user['age']??''))?>"></div><div><label>Gender</label><select name="gender"><?php foreach([''=>'Prefer not to say','male'=>'Male','female'=>'Female','other'=>'Other','prefer_not_to_say'=>'Prefer not to say'] as $v=>$label):?><option value="<?=escapeHtml($v)?>" <?=$user['gender']===$v?'selected':''?>><?=escapeHtml($label)?></option><?php endforeach;?></select></div><div><label>Height (cm)</label><input name="height_cm" type="number" step=".1" value="<?=escapeHtml((string)($user['height_cm']??''))?>"></div><div><label>Weight (kg)</label><input name="weight_kg" type="number" step=".1" value="<?=escapeHtml((string)($user['weight_kg']??''))?>"></div><div><label>Fitness level</label><select name="fitness_level"><?php foreach(['beginner','intermediate','advanced'] as $v):?><option value="<?=$v?>" <?=$user['fitness_level']===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></div><div><button class="button" type="submit">Save profile</button></div></form></section><?php require __DIR__.'/includes/footer.php';?>
