<?php
require_once __DIR__ . '/includes/auth.php'; requireRole('user'); $uid=(int)$_SESSION['user_id'];$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$amount=filter_var($_POST['amount_ml']??null,FILTER_VALIDATE_INT);$date=trim((string)($_POST['logged_on']??date('Y-m-d')));$valid=DateTime::createFromFormat('!Y-m-d',$date);if($amount===false||$amount<1||$amount>10000)$error='Enter an amount between 1 and 10000 ml.';elseif(!$valid||$valid->format('Y-m-d')!==$date)$error='Choose a valid date.';else{$q=$pdo->prepare('INSERT INTO water_logs(user_id,logged_on,amount_ml) VALUES(?,?,?)');$q->execute([$uid,$date,$amount]);redirect('water.php');}}
$q=$pdo->prepare('SELECT COALESCE(SUM(amount_ml),0) FROM water_logs WHERE user_id=? AND logged_on=CURDATE()');$q->execute([$uid]);$today=(int)$q->fetchColumn();$q=$pdo->prepare('SELECT logged_on,SUM(amount_ml) total_ml,COUNT(*) entries FROM water_logs WHERE user_id=? GROUP BY logged_on ORDER BY logged_on DESC LIMIT 30');$q->execute([$uid]);$rows=$q->fetchAll();$pageTitle='Water log';require __DIR__.'/includes/header.php';
?>
<section class="page-heading"><div><p class="eyebrow">STAY HYDRATED</p><h1>Water log</h1><p>Record your water intake each day.</p></div></section>
<section class="stats-grid"><article class="stat-card"><p>Today's water intake</p><h2><?=number_format($today)?> ml</h2><p><?=number_format($today/1000,2)?> litres</p></article></section>
<section class="panel"><h2>Add water</h2><?php if($error):?><div class="alert error"><?=escapeHtml($error)?></div><?php endif;?><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=escapeHtml(csrfToken())?>"><div><label>Date</label><input type="date" name="logged_on" value="<?=date('Y-m-d')?>" required></div><div><label>Amount (ml)</label><input type="number" name="amount_ml" min="1" max="10000" step="1" required></div><div><button class="button" type="submit">Add water</button></div></form></section>
<section class="panel"><h2>Daily history</h2><?php if(!$rows):?><p>No water logged yet.</p><?php else:?><div class="table-wrap"><table><thead><tr><th>Date</th><th>Total</th><th>Entries</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=escapeHtml($r['logged_on'])?></td><td><?=number_format((int)$r['total_ml'])?> ml</td><td><?=(int)$r['entries']?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php require __DIR__.'/includes/footer.php';?>
